apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taiga.fullname" . }}
  labels:
{{ include "taiga.labels" . | indent 4 }}
data:
  conf.json: |
    {
        "api": "{{ include "taiga.scheme" . }}://{{ include "taiga.hostname" . }}/api/v1/",
        "eventsUrl": null,
        "eventsMaxMissedHeartbeats": 5,
        "eventsHeartbeatIntervalTime": 60000,
        "eventsReconnectTryInterval": 10000,
        "debug": {{ .Values.taiga.debug }},
        "debugInfo": false,
        "defaultLanguage": "en",
        "themes": ["taiga", "material-design"],
        "defaultTheme": "taiga",
        "publicRegisterEnabled": true,
        "feedbackEnabled": {{ .Values.taiga.feedback.enabled }},
        "supportUrl": "{{ .Values.taiga.support }}",
        "privacyPolicyUrl": null,
        "termsOfServiceUrl": null,
        "GDPRUrl": null,
        "maxUploadFileSize": null,
        "contribPlugins": [],
        "tribeHost": null,
        "importers": [],
        "gravatar": {{ .Values.taiga.gravatar }},
        "rtlLanguages": ["fa"]
    }

  local.py: |
    from .development import *
    
    DEBUG = {{- if .Values.taiga.debug }} True {{- else }} False {{- end }}
    
    #ADMINS = (
    #    ("Admin", "example@example.com"),
    #)
    
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "{{ .Values.postgresql.postgresqlDatabase }}",
            "HOST": "{{ template "postgresql.hostname" . }}",
            "USER": "{{ .Values.postgresql.postgresqlUsername }}",
            "PASSWORD": "{{ .Values.postgresql.postgresqlPassword }}",
        }
    }
    
    SITES = {
        "api": {
           "scheme": "http",
           "domain": "localhost:8000",
           "name": "api"
        },
        "front": {
           "scheme": "{{ include "taiga.scheme" . }}",
           "domain": "{{ include "taiga.hostname" . }}",
           "name": "front"
        },
    }

    {{- if .Values.taiga.email.enabled }}
    DEFAULT_FROM_EMAIL =  '{{ .Values.taiga.email.from }}' 
    #CHANGE_NOTIFICATIONS_MIN_INTERVAL = {{ .Values.taiga.email.notificationMinInterval }} #seconds

    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_USE_TLS = {{- if .Values.taiga.email.tls }}True{{- else }}False{{- end }}
    EMAIL_HOST = '{{ .Values.taiga.email.host }}'
    EMAIL_PORT = '{{ .Values.taiga.email.port }}'
    EMAIL_HOST_USER = '{{ .Values.taiga.email.user }}'
    EMAIL_HOST_PASSWORD = '{{ .Values.taiga.email.password }}'
    {{- end }}

    PUBLIC_REGISTER_ENABLED = {{- if .Values.taiga.publicRegister }} True {{- else }} False {{- end }}

    {{- if .Values.taiga.feedback.enabled }}
    FEEDBACK_ENABLED = True
    FEEDBACK_EMAIL = "{{ .Values.taiga.feedback.email }}" 
    {{- end }}

    MEDIA_URL = "{{ include "taiga.scheme" . }}://{{ include "taiga.hostname" . }}/media/"
    STATIC_URL = "{{ include "taiga.scheme" . }}://{{ include "taiga.hostname" . }}/static/"

